import Head from 'next/head'
import { ThemeProvider, createTheme } from "@mui/material/styles"
import { useDarkMode } from '../../provider/DarkMode'


export default function Layout({children}) {

  const { darkMode } = useDarkMode()

  const theme = createTheme({
    palette: {
      ...(darkMode
        ? {
          mode: "dark",
          primary: {
            main: "#808080",
            light: "#808080",
            dark: "#808080"
          },
          text: {
            primary: "#c3c3c3"
          },
          backColor: "#1a1a1a"
          }
        : {
          mode: "light",
          primary: {
            main: "#7EBA00"
          },
          backColor: "#fff"
        }
      ),
    },
    components: {
      MuiButton: {
        styleOverrides: {
          root: {
            color: "#fff"
          },
        },
      },
    },
    typography: {
      subtitle1: {
        fontSize: "20px",
        color: darkMode ? "#c3c3c3":"#000"
      }
    }
  })

  return(
  <ThemeProvider theme={theme} >
    <Head>
      <title>Leandror</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      {children}
  </ThemeProvider>
  )

}